apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smart-contract.configMapNameSmartContractInfo" . }}
  namespace: {{ template "smart-contract.namespace" . }}
  annotations:
    "description": "Deployed Smart Contracts info"
  labels:
    {{- include "smart-contract.labels" . | nindent 4 }}